<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <HeurexWithTestOrdering>False</HeurexWithTestOrdering>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GnuCash.DotNet.Protocol\GnuCash.DotNet.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoNSubstitute" />
    <PackageReference Include="AutoFixture.Xunit3" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.analyzers" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(HeurexWithTestOrdering)' == 'true'">
    <PackageReference Include="Xunit.v3.Priority" PrivateAssets="all" />
  </ItemGroup>
</Project>
